[package]
authors = ["nephtys <christopher.kaag@gmail.com>"]
name = "beerlist-rustix"
version = "0.1.0"
[dependencies]
custom_derive = "0.1.7"
derive_builder = "0.5.0"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_json = "1.0.2"
