[package]
name = "blrustix"
version = "0.2.0"
authors = ["nephtys <christopher.kaag@gmail.com>"]

[dependencies]
bincode = "0.8.0"
custom_derive = "0.1.7"
derive_builder = "0.5.0"
lmdb = "0.7.1"
quick-error = "1.2.0"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_json = "1.0.2"
